theme: jekyll-theme-minimal
source: https://github.com/BNK3R-Boy/VMR_AutoBalancer
logo: https://repository-images.githubusercontent.com/307451299/41f13b00-180a-11eb-9ce3-3207387c8c54
show_downloads: true
